import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Search,BookOpen,Library,FileText,GitCompare,Bookmark,ChevronRight,Clock3,Sparkles,Plus,ExternalLink,Menu,X,Check,SlidersHorizontal,ArrowUpRight,Trash2} from "lucide-react";
import "./styles.css";

const PAPERS=[
 {id:1,title:"AIOS: LLM Agent Operating System",authors:"Tianyu Mei, et al.",year:2025,venue:"COLM",tags:["Agents","Operating Systems"],abstract:"AIOS explores an operating-system layer designed around large language model agents, with services for memory, planning, tool use and task execution.",score:98,citations:42},
 {id:2,title:"A Semantic File System for AIOS",authors:"Y. Shi, et al.",year:2025,venue:"ICLR",tags:["Semantic FS","AIOS"],abstract:"A semantic file system organizes resources around meaning and relationships so agents can retrieve context without depending on exact paths or filenames.",score:95,citations:18},
 {id:3,title:"WindowsAgentArena: Evaluating OS Agents at Scale",authors:"X. Zhou, et al.",year:2024,venue:"NeurIPS",tags:["OS Agents","Benchmark"],abstract:"A benchmark for evaluating multimodal agents on realistic computer tasks, highlighting the gap between agent automation and human performance.",score:91,citations:73},
 {id:4,title:"RAGAS: Automated Evaluation of Retrieval Augmented Generation",authors:"Shahul Es, et al.",year:2024,venue:"EACL",tags:["RAG","Evaluation"],abstract:"An evaluation framework for measuring faithfulness, answer relevance and retrieval quality in retrieval-augmented generation systems.",score:88,citations:120},
 {id:5,title:"Toolformer: Language Models Can Teach Themselves to Use Tools",authors:"Timo Schick, et al.",year:2023,venue:"NeurIPS",tags:["Tool Use","LLMs"],abstract:"Shows how language models can learn to decide when and how to call external tools, enabling more useful task-oriented behavior.",score:84,citations:980}
];

function App(){
 const [tab,setTab]=useState("Discover"),[query,setQuery]=useState(""),[selected,setSelected]=useState(PAPERS[0]),[saved,setSaved]=useState([]),[compare,setCompare]=useState([]),[mobile,setMobile]=useState(false),[notes,setNotes]=useState(""),[toast,setToast]=useState("");
 const results=useMemo(()=>{const q=query.toLowerCase().trim(); if(!q)return PAPERS; return PAPERS.filter(p=>(p.title+" "+p.authors+" "+p.abstract+" "+p.tags.join(" ")).toLowerCase().includes(q));},[query]);
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const toggleSave=(id)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const toggleCompare=(id)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:c);
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="logo"><Sparkles size={18}/></div><div><b>OpenResearch</b><span>AI research workspace</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
   <nav>{["Discover","Library","Reader","Compare"].map(x=><button key={x} className={tab===x?"nav active":"nav"} onClick={()=>{setTab(x);setMobile(false)}}>{x==="Discover"?<Search/>:x==="Library"?<Library/>:x==="Reader"?<BookOpen/>:<GitCompare/>}{x}<span>{x==="Library"&&saved.length?saved.length:""}</span></button>)}</nav>
   <div className="side-card"><Sparkles size={16}/><b>Research Copilot</b><p>Find gaps, connect papers and turn evidence into structured notes.</p><button onClick={()=>notify("Copilot workspace opened")}>Open Copilot <ArrowUpRight size={14}/></button></div>
   <div className="profile"><div className="avatar">K</div><div><b>Researcher</b><span>Personal workspace</span></div></div>
  </aside>
  <main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">{tab}<ChevronRight size={15}/><span>{selected.title}</span></div><button className="header-btn" onClick={()=>notify("Import dialog ready")}><Plus size={17}/> Import</button></header>
   {tab==="Discover"&&<section className="content"><div className="hero"><div><div className="eyebrow"><Sparkles size={14}/> RESEARCH INTELLIGENCE</div><h1>Research, without<br/><em>the busywork.</em></h1><p>Discover papers, understand evidence, compare ideas, and build a research trail from one focused workspace.</p></div><div className="hero-art"><div className="orb o1"/><div className="orb o2"/><div className="orb o3"/><div className="art-label">5 papers<br/><span>in context</span></div></div></div>
    <div className="searchbar"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search papers, concepts, authors, or ask a research question..."/><kbd>⌘ K</kbd><button><SlidersHorizontal size={17}/></button></div>
    <div className="section-head"><div><h2>{query?"Search results":"Recommended for your research"}</h2><p>{results.length} papers in your current evidence set</p></div><button className="text-btn">View all <ChevronRight size={16}/></button></div>
    <div className="paper-grid">{results.map(p=><PaperCard key={p.id} p={p} selected={selected.id===p.id} saved={saved.includes(p.id)} compared={compare.includes(p.id)} onOpen={()=>{setSelected(p);setTab("Reader")}} onSave={()=>toggleSave(p.id)} onCompare={()=>toggleCompare(p.id)}/>)}</div>
   </section>}
   {tab==="Library"&&<LibraryView papers={PAPERS.filter(p=>saved.includes(p.id))} onOpen={p=>{setSelected(p);setTab("Reader")}} onRemove={id=>toggleSave(id)}/>}
   {tab==="Reader"&&<Reader p={selected} saved={saved.includes(selected.id)} onSave={()=>toggleSave(selected.id)} notes={notes} setNotes={setNotes} notify={notify}/>}
   {tab==="Compare"&&<Compare papers={PAPERS.filter(p=>compare.includes(p.id))} onOpen={p=>{setSelected(p);setTab("Reader")}}/>}
  </main>
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}

function PaperCard({p,selected,saved,compared,onOpen,onSave,onCompare}){return <article className={selected?"paper selected":"paper"} onClick={onOpen}><div className="paper-top"><span className="type">PAPER</span><button className={saved?"icon saved":"icon"} onClick={e=>{e.stopPropagation();onSave()}}><Bookmark size={16} fill={saved?"currentColor":"none"}/></button></div><h3>{p.title}</h3><p className="authors">{p.authors} · {p.year} · {p.venue}</p><p className="abstract">{p.abstract}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="paper-foot"><span><span className="score">{p.score}</span> relevance</span><button className={compared?"compare on":"compare"} onClick={e=>{e.stopPropagation();onCompare()}}><GitCompare size={14}/>{compared?"Compared":"Compare"}</button></div></article>}

function LibraryView({papers,onOpen,onRemove}){return <section className="content"><div className="page-title"><div><div className="eyebrow"><Library size={14}/> YOUR LIBRARY</div><h1>Saved research</h1><p>Your curated evidence set, ready for deeper reading.</p></div><button className="header-btn"><Plus size={17}/> Add collection</button></div>{papers.length?<div className="list">{papers.map(p=><div className="list-row" key={p.id} onClick={()=>onOpen(p)}><div className="mini-doc"><FileText/></div><div className="row-main"><b>{p.title}</b><span>{p.authors} · {p.year}</span></div><span className="row-tag">{p.venue}</span><button className="icon" onClick={e=>{e.stopPropagation();onRemove(p.id)}}><Trash2 size={16}/></button><ChevronRight size={17}/></div>)}</div>:<Empty title="Your library is empty" text="Bookmark papers from Discover to build your evidence set."/>}</section>}

function Reader({p,saved,onSave,notes,setNotes,notify}){return <section className="content reader"><div className="reader-head"><div><span className="type">RESEARCH PAPER</span><h1>{p.title}</h1><p>{p.authors} · {p.year} · {p.venue}</p></div><div className="actions"><button className="header-btn" onClick={onSave}><Bookmark size={16} fill={saved?"currentColor":"none"}/>{saved?"Saved":"Save"}</button><button className="header-btn primary" onClick={()=>notify("Citation copied to clipboard")}><FileText size={16}/> Cite</button></div></div><div className="reader-layout"><article className="paper-body"><div className="ai-summary"><Sparkles/><div><b>AI research brief</b><p>{p.abstract}</p><div className="brief-stats"><span>Relevance <b>{p.score}%</b></span><span>Citations <b>{p.citations}</b></span><span>Published <b>{p.year}</b></span></div></div></div><h2>Abstract</h2><p>{p.abstract} This workspace turns the paper into a structured evidence object so you can connect its claims to related work, methods, limitations, and your own research questions.</p><h2>Research signals</h2><div className="signals"><div><b>Problem</b><p>How can AI systems operate over complex research and computing environments?</p></div><div><b>Approach</b><p>Combine retrieval, structured context, tool use and evaluation around an agent workflow.</p></div><div><b>Open question</b><p>How do we improve reliability, permissions, provenance and long-horizon task execution?</p></div></div><h2>Evidence map</h2><div className="evidence"><div className="node main">Core claim</div><div className="line"/><div className="node">Method</div><div className="node">Evaluation</div><div className="node">Limitations</div></div></article><aside className="notes"><div className="notes-head"><b>Research notes</b><span>Autosaved</span></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write a note, hypothesis, or follow-up question..."/><div className="note-suggest"><Sparkles size={15}/><span>Try: “What gap does this paper leave for my VICE OS research?”</span></div></aside></div></section>}

function Compare({papers,onOpen}){return <section className="content"><div className="page-title"><div><div className="eyebrow"><GitCompare size={14}/> EVIDENCE MATRIX</div><h1>Compare research</h1><p>Put papers side-by-side to expose methods, evidence and gaps.</p></div></div>{papers.length<2?<Empty title="Select at least two papers" text="Use Compare on paper cards to build a comparison set."/>:<div className="matrix"><div className="matrix-head"><span>Dimension</span>{papers.map(p=><button key={p.id} onClick={()=>onOpen(p)}>{p.title}</button>)}</div>{["Year","Venue","Authors","Relevance","Citations","Focus","Abstract"].map(k=><div className="matrix-row" key={k}><b>{k}</b>{papers.map(p=><div key={p.id}>{k==="Year"?p.year:k==="Venue"?p.venue:k==="Authors"?p.authors:k==="Relevance"?p.score+"%":k==="Citations"?p.citations:k==="Focus"?p.tags.join(" · "):p.abstract}</div>)}</div>)}</div>}</section>}

function Empty({title,text}){return <div className="empty"><div className="empty-icon"><FileText/></div><h2>{title}</h2><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);